const type = {
  SET_SONGURL: 'SET_SONGURL', // 设置正在播放的歌曲url
  SET_SONGINF: 'SET_SONGINF', // 设置歌曲详细信息
  SET_PLAYERLIST: 'SET_PLAYERLIST',
  ADD_SONG_TO_PLAYERLIST: 'ADD_SONG_TO_PLAYERLIST',
  SET_RECOMMENDLIST: 'SET_RECOMMENDLIST',
  SET_SONGLIST: 'SET_SONGLIST'
}
export default type
